version: "3"
services:
  nginx:
    build: ./nginx
    ports:
      - 8880:80
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./www:/www
      - phpsocket:/var/run
  php:
    build: ./php
    volumes:
      - ./php/php-fpm.d/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - ./www:/www
      - phpsocket:/var/run
volumes:
  phpsocket:
